packages:
  - 'apps/*'
  - 'packages/*'

nodeLinker: hoisted

allowBuilds:
  "@prisma/engines": true
  esbuild: true
  prisma: true
  "@parcel/watcher": true
  msw: true
  sharp: true
  workerd: true
  "@prisma/client": true

